### ISSUE TITLE
Tried playing a song and app crashed. 

### ISSUE THREAD

**Issue by neha20priya** [Bezirk-Bosch/party#25]
11-23 18:40:47.580 20663-20663/com.bosch.party E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.bosch.party, PID: 20663
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.SeekBar.getProgress()' on a null object reference
                                                                     at com.bosch.party.helper.SpotifyPlayerController.onPlaybackEvent(SpotifyPlayerController.java:291)
                                                                     at com.spotify.sdk.android.player.Player$28.run(Player.java:1164)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by neha20priya** [comment]
Resolved
